name: rideshare_app
description: A community-driven ride-sharing mobile application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Environment Variables
  flutter_dotenv: ^5.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Location & Maps
  geolocator: ^10.1.0
  flutter_map: ^6.1.0
  
  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.2.1
  permission_handler: ^11.0.1
  
  # Real-time Communication
  web_socket_channel: ^2.4.0
  
  # Image Handling
  image_picker: ^1.0.4
  
  # Notifications
  # flutter_local_notifications: ^16.1.0  # Temporarily disabled due to Android compilation issues

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - .env
  

